import type { Metadata } from "next";
import { ThemeProvider } from "@app/providers";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModeToggle } from "@app/components/toggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          <div>
            <ModeToggle />
          </div>
          {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
